pinpong.IR_callbackUser(function (message) {
    if (message == 9) {
        pinpong.setRelay(RELAY.CLOSE)
    } else if (message == 13) {
        pinpong.setRelay(RELAY.DISCON)
    }
})
pinpong.initDisplay()
pinpong.AHT20Init()
pinpong.setIndexColor(pinpong.ledRange(1, 2), 0xff0000)
pinpong.OLEDshowUserText("M1CW", 0, 0)
pinpong.motorRun(MOTOR.M1, DIRECTION.CW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("M1CCW", 0, 5)
pinpong.motorRun(MOTOR.M1, DIRECTION.CCW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("Stop1", 0, 11)
pinpong.motorStop(MOTOR.M1)
basic.pause(2000)
pinpong.setIndexColor(pinpong.ledRange(1, 2), 0xff8000)
pinpong.OLEDshowUserText("M2CW", 1, 0)
pinpong.motorRun(MOTOR.M2, DIRECTION.CW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("M2CCW", 1, 5)
pinpong.motorRun(MOTOR.M2, DIRECTION.CCW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("Stop2", 1, 11)
pinpong.motorStop(MOTOR.M2)
basic.pause(2000)
pinpong.setIndexColor(pinpong.ledRange(1, 2), 0xb09eff)
pinpong.OLEDshowUserText("M3CW", 2, 0)
pinpong.motorRun(MOTOR.M3, DIRECTION.CW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("M3CCW", 2, 5)
pinpong.motorRun(MOTOR.M3, DIRECTION.CCW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("Stop3", 2, 11)
pinpong.motorStop(MOTOR.M3)
basic.pause(2000)
pinpong.setIndexColor(pinpong.ledRange(1, 2), 0x00ffff)
pinpong.OLEDshowUserText("M4CW", 3, 0)
pinpong.motorRun(MOTOR.M4, DIRECTION.CW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("M4CCW", 3, 5)
pinpong.motorRun(MOTOR.M4, DIRECTION.CCW, 255)
basic.pause(2000)
pinpong.OLEDshowUserText("Stop4", 3, 11)
pinpong.motorStop(MOTOR.M4)
basic.pause(2000)
pinpong.setIndexColor(pinpong.ledRange(1, 2), 0xff0080)
basic.forever(function () {
    pinpong.motorRun(MOTOR.M1, DIRECTION.CW, 50)
    basic.pause(1000)
    pinpong.motorRun(MOTOR.M1, DIRECTION.CCW, 50)
    basic.pause(1000)
})

basic.forever(function () {
    pinpong.clear(4, 3, 6)
    pinpong.OLEDshowUserText("AE:" + pinpong.readAngle(), 4, 0)
    pinpong.clear(5, 3, 6)
    pinpong.OLEDshowUserText("FE:" + pinpong.readFlre(), 5, 0)
    pinpong.clear(6, 14, 16)
    pinpong.OLEDshowUserText("IR:" + pinpong.IR_read(), 6, 11)
    pinpong.clear(6, 3, 4)
    pinpong.OLEDshowUserText("MD:" + pinpong.motorState(MOTOR.M1, STATE.DIR), 6, 0)
    pinpong.clear(6, 8, 11)
    pinpong.OLEDshowUserText("MS:" + pinpong.motorState(MOTOR.M1, STATE.SPEED), 6, 5)
    pinpong.clear(7, 5, 8)
    pinpong.OLEDshowUserText("TEMP:" + pinpong.readAHT20(AHT20.TEMP), 7, 0)
    pinpong.clear(7, 12, 16)
    pinpong.OLEDshowUserText("HUM:" + pinpong.readAHT20(AHT20.HUM), 7, 8)
    pinpong.OLEDshowUserText("R:" + pinpong.LEDState(LED.RD), 5, 7)
    pinpong.OLEDshowUserText("Y:" + pinpong.LEDState(LED.YW), 5, 10)
    pinpong.OLEDshowUserText("G:" + pinpong.LEDState(LED.GN), 5, 13)
    pinpong.clear(4, 10, 16)
    pinpong.OLEDshowUserText("UR:" + pinpong.Ultrasonic(), 4, 8)
})
